version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: <TASK_DEFINITION>
       LoadBalancerInfo:
         ContainerName: php-app # copy from task definition under containerDefinitions.name
         ContainerPort: 80 # an application container port 